<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Login_Member extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Anggota_Model');
    }

    public function index()
    {
		if($this->session->userdata('logined') && $this->session->userdata('logined') == true)
		{
			redirect('Member');
		}
		
		if(!$this->input->post())
		{
			$this->load->view('Member/Login_Member');
		}
		else
		{
			$login=$this->Anggota_Model->login(
				$this->input->post('nama'),
				$this->input->post('password')
			);

			if(!empty($login))
			{
				$this->session->set_userdata('nama',$login->nama);
				$this->session->set_userdata('logined',true);
				redirect("Member");
			}
			else 
			{
				redirect("Login_Member");
			}
		}
        
    } 
	
	public function logout()
    {
		$this->session->unset_userdata('logined');
		redirect("Login_Member");
    } 
    //function coba(){
    //	$this->load->view('Member/Home');
    //}
}

/* End of file Workflows.php */
/* Location: ./application/controllers/Workflows.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2017-04-15 00:43:10 */
/* http://harviacode.com */